workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Clean derived data
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build app (no signing)
        script: |
          xcodebuild -project "TodayInspiration.xcodeproj" \
            -scheme "TodayInspiration" \
            -sdk iphoneos \
            -configuration Release \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/Release-iphoneos/*.app
      - build/Release-iphoneos/*.ipa