workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Clean project
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build iOS app
        script: |
          xcodebuild -project TodayInspiration.xcodeproj \
            -scheme TodayInspiration \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/**/*.app
      - build/**/*.ipa
